function(add_sources)
   foreach(_source IN ITEMS ${ARGN})
       if (IS_ABSOLUTE "${_source}")
           set(_source_abs "${_source}")
       else()
           get_filename_component(_source_abs "${_source}" ABSOLUTE)
       endif()
       set_property(GLOBAL APPEND PROPERTY GlobalSourceList "${_source_abs}")
   endforeach()
endfunction(add_sources)

function(add_headers)
   foreach(_header IN ITEMS ${ARGN})
       if (IS_ABSOLUTE "${_header}")
           set(_header_abs "${_header}")
       else()
           get_filename_component(_header_abs "${_header}" ABSOLUTE)
       endif()
       set_property(GLOBAL APPEND PROPERTY GlobalHeaderList "${_header_abs}")
   endforeach()
endfunction(add_headers)

function(add_unit_sources)
   foreach(_unit_source IN ITEMS ${ARGN})
       if (IS_ABSOLUTE "${_unit_source}")
           set(_unit_source_abs "${_unit_source}")
       else()
           get_filename_component(_unit_source_abs "${_unit_source}" ABSOLUTE)
       endif()
       set_property(GLOBAL APPEND PROPERTY GlobalUnitSourceList "${_unit_source_abs}")
   endforeach()
endfunction(add_unit_sources)

function(add_unit_headers)
   foreach(_unit_header IN ITEMS ${ARGN})
       if (IS_ABSOLUTE "${_unit_header}")
           set(_unit_header_abs "${_unit_header}")
       else()
           get_filename_component(_unit_header_abs "${_unit_header}" ABSOLUTE)
       endif()
       set_property(GLOBAL APPEND PROPERTY GlobalUnitHeaderList "${_unit_header_abs}")
   endforeach()
endfunction(add_unit_headers)
