name: Kynema-UGF-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '22'
        check-path: '.'
  CPU-Trilinos:
    needs: Formatting
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/exawind-snapshot
      env:
          EXAWIND_MANAGER: /exawind-manager
          E4S_MACHINE: true
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{github.token}}
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Tests
        run: |
          /bin/bash -c " \
            source ${EXAWIND_MANAGER}/start.sh && spack-start && \
            spack env activate e4s-build && \
            cd ${EXAWIND_MANAGER}/environments/e4s-build && \
            ln -s ${GITHUB_WORKSPACE} kynema-ugf && \
            spack develop --no-modify-concrete-specs --no-clone kynema-ugf@=master && \
            spack rm exawind && \
            spack add kynema-ugf@master+hypre+openfast+tioga+trilinos-solvers && \
            spack concretize -f && \
            spack install --reuse && \
            spack cd -b kynema-ugf && \
            spack build-env kynema-ugf ctest -j $(nproc) -L unit --output-on-failure \
          "
  CPU-Hypre-Only:
    needs: Formatting
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/exawind-snapshot
      env:
          EXAWIND_MANAGER: /exawind-manager
          E4S_MACHINE: true
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{github.token}}
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Tests
        run: |
          /bin/bash -c " \
            source ${EXAWIND_MANAGER}/start.sh && spack-start && \
            spack env activate e4s-build && \
            cd ${EXAWIND_MANAGER}/environments/e4s-build && \
            ln -s ${GITHUB_WORKSPACE} kynema-ugf && \
            spack develop --no-modify-concrete-specs --no-clone kynema-ugf@=master && \
            spack rm exawind && \
            spack add kynema-ugf@master+hypre+openfast+tioga~trilinos-solvers && \
            spack concretize -f && \
            spack install && \
            spack cd -b kynema-ugf && \
            spack build-env kynema-ugf ctest -j $(nproc) -L unit --output-on-failure \
          "
